_BASE_:
  [
    "/workspace/open-images-v7/coco_annotations/open-images-v7_coco.yml",
    "../runtime.yml",
    "_base_/picodet_v2.yml",
    "_base_/optimizer_300e.yml",
    "_base_/picodet_416_reader.yml",
  ]

weights: output/picodet_m_416_coco_haramblur/best_model
find_unused_parameters: True
use_ema: true
epoch: 2000
snapshot_epoch: 50

TrainReader:
  # best batch size to prevent RTX A4500 GPU out of memory
  batch_size: 64

LearningRate:
  base_lr: 0.08
  schedulers:
    - name: CosineDecay
      max_epochs: 2000
    - name: LinearWarmup
      start_factor: 0.1
      steps: 300
