_BASE_: [
  '../datasets/bird_detection_coco.yml',
  '../runtime.yml',
  '_base_/picodet_v2.yml',
  '_base_/optimizer_300e.yml',
  '_base_/picodet_320_reader.yml',
]

pretrain_weights: https://paddledet.bj.bcebos.com/models/picodet_s_320_coco_lcnet.pdparams
save_dir: output/picodet_s_320_bird_detection
weights: output/picodet_s_320_bird_detection/best_model
find_unused_parameters: True
use_ema: true
epoch: 150
snapshot_epoch: 5

LCNet:
  scale: 0.75
  feature_maps: [3, 4, 5]

LCPAN:
  out_channels: 96

PicoHeadV2:
  conv_feat:
    name: PicoFeat
    feat_in: 96
    feat_out: 96
    num_convs: 2
    num_fpn_stride: 4
    norm_type: bn
    share_cls_reg: True
    use_se: True
  feat_in_chan: 96

TrainReader:
  batch_size: 16

LearningRate:
  base_lr: 0.08
  schedulers:
  - !CosineDecay
    max_epochs: 150
  - !LinearWarmup
    start_factor: 0.1
    steps: 300
